plugins {
    alias(libs.plugins.moviedatabase.android.library)
    alias(libs.plugins.moviedatabase.android.library.compose)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.kotlin.kover)
}

apply from: "$rootDir/android-test-dependencies.gradle"

android {
    namespace "io.viewpoint.moviedatabase.ui.common"
}

dependencies {
    implementation project(':core:resources')

    implementation project(':core:common')
    implementation project(':core:widget')
    implementation project(':core:model')
    implementation project(':core:domain')

    implementation project(':core:designsystem')

    // androidx
    implementation libs.androidx.core
    implementation libs.androidx.activity.compose
    implementation libs.androidx.fragment
    implementation libs.androidx.appcompat
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.paging
    implementation libs.androidx.paging.compose

    // compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.uigraphics
    implementation libs.androidx.material3.compose
    implementation libs.compose.tooling.preview
    debugImplementation libs.compose.tooling

    // coil
    implementation libs.coil
    implementation libs.coil.okhttp

    // dagger/hilt
    implementation libs.hilt
    kapt libs.hilt.kapt
    // hilt with androidx
    kapt libs.androidx.hilt.kapt

    // timber
    implementation libs.timber
}
