plugins {
    alias(libs.plugins.moviedatabase.jvm.library)
    alias(libs.plugins.kotlin.kapt)
}

dependencies {
    implementation libs.kotlinx.coroutines.core
    implementation libs.moshi

    implementation project(':core:model')
    implementation project(':core:api')

    implementation project(':test:common')
}