plugins {
    alias(libs.plugins.moviedatabase.android.library)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.kotlin.kover)
}

apply from: "$rootDir/android-jacoco.gradle"
apply from: "$rootDir/android-test-dependencies.gradle"

android {
    namespace "io.viewpoint.moviedatabase.common"
}

dependencies {
    implementation project(':core:resources')

    implementation libs.androidx.core

    // timber
    implementation libs.timber

    // glide
    implementation libs.glide
    kapt libs.glide.kapt
}

kover {
    currentProject {
        createVariant("merged") {
            add(["debug"], false)
        }
    }
}
