plugins {
    alias(libs.plugins.moviedatabase.jvm.library)
    alias(libs.plugins.kotlin.kapt)
}

apply from: "$rootDir/java-test-dependencies.gradle"

dependencies {
    implementation libs.moshi
    implementation libs.okhttp.logging
    implementation libs.retrofit
    implementation libs.retrofit.moshi
    implementation libs.kotlinx.coroutines.core

    testImplementation libs.test.mockwebserver
}
