plugins {
    id 'java-library'
    id 'kotlin'
    alias(libs.plugins.kotlin.kover)
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}

compileTestKotlin {
    kotlinOptions {
        jvmTarget = "17"
    }
}

sourceCompatibility = "17"
targetCompatibility = "17"

dependencies {
}

kover {
    currentProject {
        createVariant("merged") {
            add(["jvm"], false)
        }
    }
}
