plugins {
    alias(libs.plugins.moviedatabase.android.application)
    alias(libs.plugins.moviedatabase.android.application.compose)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.kotlin.kapt)
}

apply from: '../android-test-dependencies.gradle'

android {
    namespace "io.viewpoint.moviedatabase"

    defaultConfig {
        applicationId "io.viewpoint.moviedatabase"
    }

    signingConfigs {
        releaseKeystore {
            Properties prop = new Properties()
            prop.load(project.rootProject.file('keystore.properties').newDataInputStream())
            storeFile project.rootProject.file('debug.keystore')
            storePassword prop.getProperty('storePassword')
            keyAlias prop.getProperty('keyAlias')
            keyPassword prop.getProperty('keyPassword')
        }
    }

    buildTypes {
        debug {
        }
        release {
            signingConfig signingConfigs.releaseKeystore

            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFiles fileTree(dir: 'proguard', include: ['*.pro']).asList().toArray()
        }
    }
}

kapt {
    correctErrorTypes true // for hilt
}

dependencies {
    implementation project(':core:resources')

    implementation project(':core:common')
    implementation project(':core:model')
    implementation project(':core:data')
    implementation project(':core:domain')
    implementation project(':core:designsystem')
    implementation project(':core:preferences')

    // features
    implementation project(':feature:common-ui')
    implementation project(':feature:home')
    implementation project(':feature:search')
    implementation project(':feature:setting')

    // androidx
    implementation libs.androidx.core
    implementation libs.androidx.activity
    implementation libs.androidx.activity.compose
    implementation libs.androidx.fragment
    implementation libs.androidx.appcompat
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.startup
    implementation libs.androidx.paging
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.navigation.compose
    implementation libs.androidx.workmanager
    implementation libs.androidx.hilt.work
    implementation libs.androidx.hilt.navigation.compose

    // compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.uigraphics
    implementation libs.androidx.material3.compose
    implementation libs.compose.tooling.preview
    debugImplementation libs.compose.tooling

    // androidx.room
    implementation libs.androidx.room.runtime
    implementation libs.androidx.room
    kapt libs.androidx.room.compiler

    // dagger/hilt
    implementation libs.hilt
    kapt libs.hilt.kapt
    // hilt with androidx
    kapt libs.androidx.hilt.kapt

    // timber
    implementation libs.timber

    // coil
    implementation libs.coil
    implementation libs.coil.okhttp

    // okhttp
    implementation libs.okhttp
}
