plugins {
    alias(libs.plugins.moviedatabase.android.library)
    alias(libs.plugins.moviedatabase.android.library.compose)
    alias(libs.plugins.kotlin.kover)
}

android {
    namespace 'io.viewpoint.moviedatabase.designsystem'
}

dependencies {
    implementation platform(libs.compose.bom)
    implementation libs.compose.ui
    implementation libs.compose.uigraphics
    implementation libs.compose.tooling.preview
    debugImplementation libs.compose.tooling

    implementation libs.androidx.material3.compose
}

kover {
    currentProject {
        createVariant("merged") {
            add(["debug"], false)
        }
    }
}
