plugins {
    alias(libs.plugins.moviedatabase.jvm.library)
    alias(libs.plugins.kotlin.kapt)
}

apply from: "$rootDir/java-test-dependencies.gradle"

dependencies {
    implementation libs.kotlinx.coroutines.core

    implementation project(':core:common-coroutines')

    implementation libs.androidx.room.common
    implementation libs.androidx.paging.common

    implementation libs.dagger
    kapt libs.dagger.kapt

    testImplementation project(':core:api')
    testImplementation project(':test:mock')
}
