name: Android CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle and Jacoco
      run: ./gradlew -PenableJacoco=true --stacktrace clean build jacocoUnitTestReport
    - name: Report Codecov
      run: bash <(curl -s https://codecov.io/bash)
    - name: Codecov
      uses: codecov/codecov-action@v1.0.11
